# -----------------------------------------------
# Print variables
macro(print_all_variables STRINGMATCH)
    message(STATUS "=====================================================")
    message(STATUS "print_all_variables---------------------------------{")
    get_cmake_property(_variableNames VARIABLES)

    set(_variablesOfInterest "")
    if("${STRINGMATCH}" STREQUAL "all")
        set(_variablesOfInterest ${_variableNames})
    else()
        foreach(_variableName "${_variableNames}")
            if("${_variableName}" MATCHES "${STRINGMATCH}")
                list(APPEND ${_variablesOfInterest} "${_variableName}")
            endif()
        endforeach(_variableName "${_variableNames}")
    endif()

    message(STATUS "${_variablesOfInterest}")

    foreach(_variableName ${_variablesOfInterest})
        # ignoring some variables here
        if("${_variableName}" STREQUAL "CMAKE_CXX_COMPILER_ID_PLATFORM_CONTENT")
            message(STATUS "Ignored CMAKE_CXX_COMPILER_ID_PLATFORM_CONTENT")
        else()
            message(STATUS "${_variableName}=${${_variableName}}")
        endif()
    endforeach(_variableName ${_variablesOfInterest})
    message(STATUS "print_all_variables---------------------------------}")
    message(STATUS "=====================================================")
endmacro()

function(dump_cmake_variables)
    get_cmake_property(_variableNames VARIABLES)
    list (SORT _variableNames)
    foreach (_variableName ${_variableNames})
        if (ARGV0)
            unset(MATCHED)
            string(REGEX MATCH ${ARGV0} MATCHED ${_variableName})
            if (NOT MATCHED)
                continue()
            endif()
        endif()
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
endfunction()